<a href="https://colab.research.google.com/github/Ayeshaaa777/numpy_learn/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [10]:
arr2 = np.array([[1,2,3],[4,5,6]]) # 2 square brackets indictate 2d array
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
arr3 = np.array([[[1,2,3],[3,4,5],[5,6,7]]]) # 3 square brackets indicate 3d array
print(arr3)

[[[1 2 3]
  [3 4 5]
  [5 6 7]]]


In [16]:
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)


Array created using passed tuple:
 [1 3 2]


In [21]:
print(arr.ndim)
print(arr1.ndim) # dimensions of the array
print(arr2.ndim)
print(arr3.ndim)
print(arr3.shape)

1
1
2
3
(1, 3, 3)


In [23]:
# 3d array with 3 planes
import numpy as np

arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                  [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [24]:
print(arr3d.ndim)
print(arr3d.shape)

3
(3, 3, 3)


In [25]:
print(arr3d.dtype)     # float64
print(arr3d.itemsize)  # 8 (float64 is an 8 byte quantity)
print(arr3d.data)      # <memory at XXXX>

int64
8
